// Feature flags used within the app are defined here.
export enum FeatureFlag {
  EXAMPLE_FEATURE = 'EXAMPLE_FEATURE',
  TWO_FACTOR_AUTH = 'TWO_FACTOR_AUTH',
  REPORTS_MODULE = 'REPORTS_MODULE',
  HISTORY_MODULE = 'HISTORY_MODULE',
  CHATS_MODULE = 'CHATS_MODULE',
  MEMBERS_MANAGEMENT = 'MEMBERS_MANAGEMENT',
  WEBHOOKS_MODULE = 'WEBHOOKS_MODULE',
  INTEGRATIONS_MODULE = 'INTEGRATIONS_MODULE',
}
