export enum IntegrationEnum {
  ZAPIER = 'zapier',
  SHOPIFY = 'shopify',
}

export enum IntegrationType {
  WEBHOOK_URL = 'WEBHOOK_URL',
  API_KEY = 'API_KEY',
  SHOPIFY_URL = 'SHOPIFY_URL',
  SHOPIFY_ACCESS_TOKEN = 'SHOPIFY_ACCESS_TOKEN',
  STRIPE_SECRET_LIVE_KEY = 'STRIPE_SECRET_LIVE_KEY',
  STRIPE_SECRET_TEST_KEY = 'STRIPE_SECRET_TEST_KEY',
  MERCADO_PAGO_PRODUCTION_ACCESS_TOKEN = 'MERCADO_PAGO_PRODUCTION_ACCESS_TOKEN',
  MERCADO_PAGO_PUBLIC_PRODUCTION_KEY = 'MERCADO_PAGO_PUBLIC_PRODUCTION_KEY',
  MERCADO_PAGO_SANDBOX_ACCESS_TOKEN = 'MERCADO_PAGO_SANDBOX_ACCESS_TOKEN',
  MERCADO_PAGO_PUBLIC_SANDBOX_KEY = 'MERCADO_PAGO_PUBLIC_SANDBOX_KEY',
  WOOCOMMERCE_API_URL = 'WOOCOMMERCE_API_URL',
  WOOCOMMERCE_CONSUMER_KEY = 'WOOCOMMERCE_CONSUMER_KEY',
  WOOCOMMERCE_CONSUMER_SECRET = 'WOOCOMMERCE_CONSUMER_SECRET',
}

export enum IntegrationResponseStatus {
  SUCCESS = 'success',
  FAILURE = 'failure',
  PENDING = 'pending',
  ERROR = 'error',
  NOT_FOUND = 'not_found',
}

export enum WebhookPlatformEventType {
  ZAPIER_EVENT = 'ZAPIER_EVENT',
}
