name: Run semantic release

on:
  workflow_call:
    secrets:
      semantic_release_token:
        description: 'GitHub token for semantic release'
        required: true

env:
  HUSKY: 0
  GITHUB_TOKEN: ${{ secrets.semantic_release_token }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: 'Setup node with cache'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 19.0.5
          extra_plugins: |
            @semantic-release/changelog@6.0.1
            @semantic-release/git@10.0.1
            @semantic-release/github@8.0.6
            @semantic-release/exec@6.0.3
            @meltstudio/semantic-release-monorepo@2.0.0
