name: Check PR

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-commits:
    name: Lint commits
    uses: ./.github/workflows/_lint_commits.yaml

  code-checks:
    name: Run code checks and quality tools
    uses: ./.github/workflows/_code_checks.yaml
    secrets:
      turbo-team: ${{ secrets.VERCEL_ORG_ID }}
      turbo-token: ${{ secrets.VERCEL_TOKEN }}
      db_uri: ${{ secrets.DATABASE_URL }}

  deploy-web:
    name: Deploy to vercel
    uses: ./.github/workflows/_deploy_vercel.yaml
    permissions:
      contents: write
      issues: write
      pull-requests: write
    with:
      environment: Preview
      github-comment: true
      build-cache-path: apps/web
    secrets:
      vercel-team-id: ${{ secrets.VERCEL_ORG_ID }}
      vercel-project-id: ${{ secrets.VERCEL_WEB_PROJECT_ID }}
      vercel-token: ${{ secrets.VERCEL_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
